site_name: ini.h
site_url: https://giosali.github.io/ini.h/
site_author: Giovanni Salinas
site_description: A single-header library for reading and writing INI files in C++
repo_name: giosali/ini.h
repo_url: https://github.com/giosali/ini.h
edit_uri: ""

theme:
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: dracula
    primary: pink
    accent: pink

nav:
  - Home: index.md
  - API:
    - ini: api/ini_namespace.md
    - File:
      - File: api/file/file.md
      - Constructors: api/file/constructors.md
      - Functions:
        - add_section: api/file/functions/add_section.md
        - clear: api/file/functions/clear.md
        - empty: api/file/functions/empty.md
        - has_section: api/file/functions/has_section.md
        - remove_section: api/file/functions/remove_section.md
        - rename_section: api/file/functions/rename_section.md
        - size: api/file/functions/size.md
        - write: api/file/functions/write.md
    - Section:
      - Section: api/section/section.md
      - Constructors: api/section/constructors.md
      - Functions:
        - clear: api/section/functions/clear.md
    - load: api/load.md
    - open: api/open.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocs_pymdownx_material_extras