name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install -r requirements.txt
          mkdocs gh-deploy --force