name: macOS Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'ext/**'
      - '*.md'
      - '*.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'ext/**'
      - '*.md'
      - '*.yml'

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: test
        run: |
          cmake -S . -B build -std=c++17
          cmake --build build -std=c++17

      - name: Test
        working-directory: test/build/bin
        run: ./ini_h
