name: Windows Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'ext/**'
      - '*.md'
      - '*.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'ext/**'
      - '*.md'
      - '*.yml'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ${{github.workspace}}/tests
        run: |
          cmake -S . -B build
          cmake --build build
      
      - name: Test
        working-directory: ${{github.workspace}}/tests/build/bin
        run: ./ini_h